create or replace user gautam;
grant admin to gautam;
create or replace user princy;
grant foodManager to princy;
create or replace user aryan;
grant householdManager to aryan;
create or replace user ishika;
grant electronicsManager to ishika;
create or replace user kartik;
grant sportsManager to kartik;
create or replace user sakshi;
grant clothesManager to sakshi;
create or replace user mayank;
grant cashManager to mayank;
create or replace user aman;
grant foodEmployee to aman;
create or replace user sam;
grant householdEmployee to sam;
create or replace user joy;
grant electronicsEmployee to joy;
create or replace user kavi;
grant sportsEmployee to kavi;
create or replace user mandy;
grant clothesEmployee to mandy;
create or replace user payal;
grant cashier to payal;
create or replace user tony;
grant foodEmployee to tony;
create or replace user raj;
grant householdEmployee to raj;
create or replace user harsh;
grant electronicsEmployee to harsh;
create or replace user satyam;
grant sportsEmployee to satyam;
create or replace user beenu;
grant clothesEmployee to beenu;
create or replace user danny;
grant cashier to danny;
create or replace user arpit;
grant customer to arpit;
create or replace user pankaj;
grant customer to pankaj;
create or replace user presentation;
grant admin to presentation;
grant foodManager to presentation;
grant householdManager to presentation;
grant sportsManager to presentation;
grant electronicsManager to presentation;
grant clothesManager to presentation;
grant cashManager to presentation;
grant customer to presentation;
grant cashier to presentation;
grant foodEmployee to presentation;
grant householdEmployee to presentation;
grant sportsEmployee to presentation;
grant electronicsEmployee to presentation;
grant clothesEmployee to presentation;